### PR TITLE
Add maven publish plugin.

### PR DESCRIPTION
**Pull request by zhaobozhen**

### CODE REVIEW

**Comment by Goooler** [comment]
```
* Where:
Build file '/home/runner/work/LibChecker/LibChecker/build.gradle.kts' line: 1

* What went wrong:
Plugin [id: 'com.github.dcendents.android-maven-gradle-plugin', version: '2.1', apply: false] was not found in any of the following sources:

- Gradle Core Plugins (plugin is not in 'org.gradle' namespace)
- Plugin Repositories (could not resolve plugin artifact 'com.github.dcendents.android-maven-gradle-plugin:com.github.dcendents.android-maven-gradle-plugin.gradle.plugin:2.1')
  Searched in the following repositories:
    Gradle Central Plugin Repository
    Google
    MavenRepo
```

**Comment by Goooler** [comment]
Publish to `jitpack` use https://developer.android.com/studio/build/maven-publish-plugin, 
ref https://github.com/CarGuo/GSYVideoPlayer/pull/3326.

**Comment by Goooler** [comment]
Publish to `mavenCenter` use https://github.com/vanniktech/gradle-maven-publish-plugin.

**Comment by zhaobozhen** [comment]
Plan to separate sdk module to a new repo.

**Pull request closed without merging**
