### PR TITLE
Run build jobs on BuildJet-Ubuntu

### PR DESCRIPTION
**Pull request by Goooler**
https://buildjet.com/for-github-actions/blog/hardware-accelerated-android-emulator-on-buildjet-for-github-actions

### CODE REVIEW

**Comment by Goooler** [comment]
Result in https://github.com/Goooler/LibChecker/pull/4

8 cores:
```
BUILD SUCCESSFUL in 3m 52s
136 actionable tasks: 129 executed, 7 from cache

Publishing build scan...
https://gradle.com/s/qe25tswfljktc
```

16 cores:
```
BUILD SUCCESSFUL in 3m 29s
136 actionable tasks: 129 executed, 7 from cache

Publishing build scan...
https://gradle.com/s/cvihdkimrqwhs
```

**Comment by Goooler** [comment]
https://github.com/zhaobozhen/LibChecker/actions/runs/3103084875/jobs/5026029123

```
BUILD SUCCESSFUL in 9m 14s
136 actionable tasks: 101 executed, 35 from cache

Publishing build scan...
https://gradle.com/s/g5cozmfsgttio
```

**Comment by qhy040404** [comment]
Is BuildJet paid or free?

**Comment by Goooler** [comment]
Free trial minutes

**Pull request merged**
