### PR TITLE
Migrate BundleCompat to androidx official implementation

### PR DESCRIPTION
**Pull request by shawnlinboy**
getSerializable() still waiting for google adding it.

Test: Manual

### CODE REVIEW

**Review by zhaobozhen — APPROVED** [review]

**Review by zhaobozhen — CHANGES_REQUESTED** [review]
Please pass the lint check: https://github.com/LibChecker/LibChecker/actions/runs/7218909708/job/19669169315

**Comment by shawnlinboy** [comment]
This CL should not break build, it looks like something goes wrong after [this CL](https://github.com/LibChecker/LibChecker/actions/runs/7218791002/job/19668725819).

**Comment by shawnlinboy** [comment]
> Please pass the lint check: https://github.com/LibChecker/LibChecker/actions/runs/7218909708/job/19669169315

This CL should not break any builds, Lint seems like failed since [this CL](https://github.com/LibChecker/LibChecker/actions/runs/7218791002/job/19668725819).

**Comment by zhaobozhen** [comment]
> > Please pass the lint check: https://github.com/LibChecker/LibChecker/actions/runs/7218909708/job/19669169315
> 
> 
> 
> This CL should not break any builds, Lint seems like failed since [this CL](https://github.com/LibChecker/LibChecker/actions/runs/7218791002/job/19668725819).

Yes, and this PR also introduced new lint issues

**Comment by shawnlinboy** [comment]
> > > Please pass the lint check: https://github.com/LibChecker/LibChecker/actions/runs/7218909708/job/19669169315
> > 
> > 
> > This CL should not break any builds, Lint seems like failed since [this CL](https://github.com/LibChecker/LibChecker/actions/runs/7218791002/job/19668725819).
> 
> Yes, and this PR also introduced new lint issues

DONE. Please retry all checks.

**Review by zhaobozhen — APPROVED** [review]

**Comment by zhaobozhen** [comment]
Thanks!

**Pull request merged**
